
private void BtnHeavyAction_Click（object sender, EventArgs e)
{
    Debug.WriteLine("BtnHeavyAction_Click enter");
    try
    {
        Task task = HeavyActionAsync();
        // タスクが完了するまでポーリングしたりすると例外が排出されます。
        // ※ただ待ちたいだけなら await を使いましょう。
        while (task.IsCompleted) {
        }
        // await task;
    }
    catch (Exception ex)
    {
        // ここで例外がキャッチされます。
        Debug.WriteLine($"{ex.GetType().Name}:{ex.Message}");
    }
    Debug.WriteLine("BtnHeavyAction_Click exit");
}
private async Task HeavyActionAsync()
{
    Debug.WriteLine("HeavyActionAsync enter");
    await Task.Delay(3000);
    throw new Exception("HeavyActionAsyncで例外が発生しました。");
    Debug.WriteLine("HeavyActionAsync exit");
}

