
try
{
    // 何らかの処理
}
catch (Exception ex)
{
    logger.Error(ex.Message);
    logger.Error(ex.StackTrace);
}

