
public class UserService
{
    public string GetUserName(int userId)
    {
        var dataAccessor = new UserDataAccessor();

        try
        {
            var user = dataAccessor.Find(userId); // 存在しないユーザの場合はuserがnullになる
            return user.Name;  // ここで例外が発生する。本来はここの行番号をログに書きたい
        }
        catch (Exception ex)
        {
            throw new ServiceException($"ユーザ名の取得に失敗しました。 ユーザID:{userId}"); // だが、ここの行番号がログに出力される
        }
    }
}

