
            for (var i = 0; i &lt; 5; i++)
            {
                if (!context.IsReplaying) log.LogInformation($"Calling F{i}.");
                try
                {
                    await context.CallActivityAsync&lt;string&gt;("WaitTest", i);
                }
                catch (Exception e)
                {
                    if (!context.IsReplaying) log.LogError($"error orcestration: {i}", e);
                }
            }

