
        [Fact]
        public void Test_ログの確認_引数複数_失敗()
        {
            var mock = new Mock&lt;ILogger&gt;();

            Assert.True(LogTest.LogWrite(mock.Object));
            mock.Verify(x =&gt; x.Log(
            LogLevel.Warning,
            It.IsAny&lt;EventId&gt;(),
            It.Is&lt;object&gt;(o =&gt; o.ToString() == "test a:a b:b c:d"),
            null,
            It.IsAny&lt;Func&lt;object, Exception, string&gt;&gt;()), Times.Once);
        }

