More than 1 year has passed since last update.仕事で .Net Framework 4.0 を触る機会があり、その時に例外の HResult によって処理を切り替える必要があったがアクセスができなかったので理由を調べた。
忘備録として記録をしておく。Exception の HResult プロパティは .Net Framework のバージョンによってアクセス修飾子が異なる。
.Net Framework 4.5 より前では以下のようにな定義になっている。そのため HResult には直接アクセスすることができない。.Net Framework 4.5 以降では以下のような定義に変更されている。setter のみ protected になっているため例外のエラーコードに HResult プロパティから直接アクセスが可能になった。HResult にアクセスする場合は次のようにリフレクションを使用する。ただし、もしライブラリとして作成をする場合は .Net Framework 4.5 以上のプロジェクトから呼ばれる可能性もあるのでコメントのように System.Reflection.BindingFlags.Public を指定する。サンプルコードをここに上げておく。


